name: Mesagisto
main: ${main}

author: Itsusinn

api-version: 1.13
version: ${version}

lib-version: ${libVersion}
lib-download: ${libDownload}
loader-version: ${loaderVersion}

github: https://github.com/MeowCat-Studio/Mesagisto